/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        // Primary: teal-green (softer, less neon)
        'primary':                   '#35c98a',
        'primary-container':         '#1a9e6b',
        'primary-fixed':             '#52e0a2',
        'primary-fixed-dim':         '#35c98a',
        'on-primary':                '#002918',
        'on-primary-container':      '#003320',
        'on-primary-fixed':          '#001810',
        'on-primary-fixed-variant':  '#004030',
        // Secondary: steel blue (replaces neon cyan)
        'secondary':                 '#4ab8d9',
        'secondary-container':       '#2196b5',
        'secondary-fixed':           '#8dd6ef',
        'secondary-fixed-dim':       '#4ab8d9',
        'on-secondary':              '#002d38',
        'on-secondary-container':    '#003845',
        'on-secondary-fixed':        '#001820',
        'on-secondary-fixed-variant':'#004050',
        // Tertiary: warm amber (replaces coral/red)
        'tertiary':                  '#e8a44a',
        'tertiary-container':        '#c07f28',
        'tertiary-fixed':            '#f5c97a',
        'tertiary-fixed-dim':        '#e8a44a',
        'on-tertiary':               '#3c2500',
        'on-tertiary-container':     '#4a2e00',
        'on-tertiary-fixed':         '#241500',
        'on-tertiary-fixed-variant': '#5a3800',
        'background':                '#0b1326',
        'on-background':             '#dae2fd',
        'surface':                   '#0b1326',
        'surface-dim':               '#0b1326',
        'surface-bright':            '#31394d',
        'surface-container-lowest':  '#060e20',
        'surface-container-low':     '#131b2e',
        'surface-container':         '#171f33',
        'surface-container-high':    '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant':           '#2d3449',
        'surface-tint':              '#4edea3',
        'on-surface':                '#dae2fd',
        'on-surface-variant':        '#bbcabf',
        'inverse-surface':           '#dae2fd',
        'inverse-on-surface':        '#283044',
        'inverse-primary':           '#006c49',
        'outline':                   '#86948a',
        'outline-variant':           '#3c4a42',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg':      '0.25rem',
        'xl':      '0.5rem',
        '2xl':     '0.75rem',
        'full':    '0.75rem',
      },
      spacing: {
        'unit':            '4px',
        'gutter':          '16px',
        'margin-mobile':   '16px',
        'margin-desktop':  '32px',
        'container-max':   '1440px',
      },
      fontFamily: {
        'sans':    ['Inter', 'system-ui', 'sans-serif'],
        'mono':    ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        'display-lg':       ['Inter'],
        'display-lg-mobile':['Inter'],
        'headline-md':      ['Inter'],
        'headline-sm':      ['Inter'],
        'body-md':          ['Inter'],
        'body-sm':          ['Inter'],
        'label-md':         ['"JetBrains Mono"'],
      },
      fontSize: {
        'display-lg':        ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md':       ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm':       ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md':           ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm':           ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md':          ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
